version: '3'
services:

  kafkaserver:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafkaserver
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafkaserver
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "zookeeper:2181"

  producer:
    image: drugotosto84/producer:0.0.1-SNAPSHOT
    container_name: producer
    ports:
      - 8080:8080

  consumer:
    image: drugotosto84/consumer:0.0.1-SNAPSHOT
    container_name: consumer
