spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafkaserver:9092
      bindings:
        # Spring Cloud Stream (Output) Channel
        greetings-out:
          # Kafka Topic
          destination: greetings
          content-type: application/json
server:
  port: 8080


